### ISSUE TITLE
Stuck on Sending

### ISSUE THREAD

**Issue by seanaguinaga** [revolunet/react-mailchimp-subscribe#30]
Demo and my own config are stuck on sending and eventually timeout no matter what.

**Comment by lonelydatum** [comment]
I'm getting the same thing. The url works fine when I copy and paste into a new browser though.

**Comment by lonelydatum** [comment]
const bad = https://________.us20.list-manage.com/subscribe?u=________&id=________
const good = https://________.us20.list-manage.com/subscribe/post-json?u=________&id=________

I had to add the post-json

Funny because the bad url I got was literally copied and pasted from Mailchimp. (When I copied the short url)

I think the MailChimp docs could be better. They should just literally have the url for you already instead of digging through the View Source as they suggested.

**Comment by seanaguinaga** [comment]
OMG Thank you so much. yeah--- mailchimp docs....

**Comment by lonelydatum** [comment]
Nice

**Comment by revolunet** [comment]
thanks @lonelydatum

**Comment by FinnFrotscher** [comment]
+1

**Comment by otaviobps** [comment]
I'm stuck on sending too. Original URL was: `https://xxx.us16.list-manage.com/subscribe/post?u=_____&id=____`, tried changing the `post` to `post-json`, but didn't work either

**Comment by callum09** [comment]
The solution for me here was to disabled the recatpcha setting on Mailchimp's UI under the audience default settings.
